### PR TITLE
bug: Check if project-name is null

### PR DESCRIPTION
**Pull request by joel5vega**
## Pull Request description

Issue #28 

## Pull Request checklists

This PR is a:
- [x] bug-fix
- [ ] new feature
- [ ] maintenance

About this PR:
- [ ] it includes tests.
- [ ] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [ ] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:
- [x] I have reviewed the changes and it contains no misspelling.
- [x] The code is well commented, especially in the parts that contain more complexity.
- [ ] New and old tests passed locally.

## Reviewer's checklist

Copy and paste this template for your review's note:

```
## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [ ] I managed to test the new changes locally
- [ ] I confirm that the issues mentioned were fixed/resolved .
```

### CODE REVIEW

**Comment by joel5vega** [comment]
@xmnlab , I've added one conditional to check if project-name is null, please check if it is implemented correctly

**Review by xmnlab — CHANGES_REQUESTED** [review]
from the top of my head, I would say that it should be something simpler, something like

```python

default_project_name = self.defaults.get('project-name', '') or ''

````

**Comment by joel5vega** [comment]
Sure @xmnlab , I will correct and update it!

**Comment by xmnlab** [comment]
The CI is still failing about distlib issue.
I will work on that later.
But for now this PR looks good to me. Thanks

**Pull request merged**
