### PR TITLE
refactor: change to dictionary format

### PR DESCRIPTION
**Pull request by joel5vega**
changed from -name:name to name:

## Pull Request description
Change to dictionary format

refactor: Issue #43 

## Pull Request checklists

This PR is a:
- [ ] bug-fix
- [ ] new feature
- [X] maintenance

About this PR:
- [ ] it includes tests.
- [ ] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [ ] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:
- [X] I have reviewed the changes and it contains no misspelling.
- [X] The code is well commented, especially in the parts that contain more complexity.
- [ ] New and old tests passed locally.

## Additional information
image
We may need to update sugar.py as well

image

## Reviewer's checklist

Copy and paste this template for your review's note:

```
## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [ ] I managed to test the new changes locally
- [ ] I confirm that the issues mentioned were fixed/resolved .
```

### CODE REVIEW

**Comment by xmnlab** [comment]
please also update the documentation: https://github.com/osl-incubator/containers-sugar/blob/main/docs/index.md

**Comment by xmnlab** [comment]
https://github.com/osl-incubator/makim/pull/28

PS: `__main__.py` would be the "same" as our `cli.py`

**Comment by joel5vega** [comment]
> [osl-incubator/makim#28](https://github.com/osl-incubator/makim/pull/28)
> 
> PS: `__main__.py` would be the "same" as our `cli.py`
It seems that _main__.py is now in makim.py and it can be compared with sugar.py
image

**Comment by xmnlab** [comment]
@joel5vega thanks for working on that!

the linter is failing: https://github.com/osl-incubator/sugar/actions/runs/7268534099/job/19804578232?pr=97#step:5:17

in order to fix that, please run the following commands (within the sugar environment):

```bash
pre-commit install
pre-commit run --all-files
pre-commit run --all-files  # yes, run it twice to check if all the files were fixed.
```

because this issue was triggered by ruff-format, it will be fixed automatically .. 
the other hooks when fail, need to be fixed manually.

ping if you have any question

**Comment by joel5vega** [comment]
Great, it is updated

**Review by xmnlab — APPROVED** [review]
LGTM, thanks @joel5vega

**Pull request merged**
