### PR TITLE
feat: Add a new key in the root of the config file for services

### PR DESCRIPTION
**Pull request by joel5vega**
## How to test these changes
sugar build --verbose --config-file tests/containers/.services.sugar.yaml

* ```...```

## Pull Request checklists

This PR is a:
- [ ] bug-fix
- [X] new feature
- [ ] maintenance

About this PR:
- [X] it includes tests.
- [X] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [ ] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:
- [X] I have reviewed the changes and it contains no misspelling.
- [X] The code is well commented, especially in the parts that contain more complexity.
- [X] New and old tests passed locally.

## Reviewer's checklist

Copy and paste this template for your review's note:

```
## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [ ] I managed to test the new changes locally
- [ ] I confirm that the issues mentioned were fixed/resolved .
```

### CODE REVIEW

**Comment by xmnlab** [comment]
@joel5vega please rebase your branch on top of the upstream main.

now sugar.py was renamed to core.py

**Comment by joel5vega** [comment]
@xmnlab can you check if newest push solve the problem?
image

**Comment by xmnlab** [comment]
It still has merge conflicts

**Review by xmnlab — APPROVED** [review]
LGTM! thanks for working on that @joel5vega

**Pull request merged**
